sonar.projectKey=utp-secure-project
sonar.projectName=UTP Secure Project
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=sqp_947bb4ffd8523332fb567d47aa768f31110cb94e
